name: Publish to Pypi
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-publish:
    name: Build and publish to Pypi
    runs-on: ubuntu-latest
    permissions:
      # This permission is required for trusted publishing
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --only-dev

      - name: Build distribution packages
        run: uv build

      - name: Build and publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
